[profile.default]
optimizer_runs = 1000000
verbosity = 1
solc_version = '0.8.22'
out = 'out'
evm_version = 'paris'

# Extreme Fuzzing CI Profile :P
[profile.ci]
fuzz_runs = 100_000
verbosity = 4


[rpc_endpoints]
mainnet = "${MAINNET_RPC}"
sepolia = "${SEPOLIA_RPC}"
holesky = "${HOLESKY_RPC}"

[etherscan]
mainnet = {key = "${ETHERSCAN_KEY}"}
sepolia = {key = "${ETHERSCAN_KEY}"}
holesky = {key = "${ETHERSCAN_KEY}"}

